spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/transaction
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

api:
  version: v1

refreshable:
  message: hello-2